# Turns the compiled shaders listed in MANIFEST into one C++ source, OUTPUT.
#
# Run as a script (cmake -P) by spaceflight_compile_shaders().  Each manifest
# line is  symbol|stage|spirv|msl|dxbc  with an empty field where a format was
# not built on this host.

file(STRINGS "${MANIFEST}" _lines)

set(_body "// GENERATED by cmake/embed_shaders.cmake -- do not edit.\n")
string(APPEND _body "#include \"app/gfx/shader_library.hpp\"\n\n#include <cstddef>\n#include <cstdint>\n#include <string_view>\n\n")
string(APPEND _body "namespace sf::gfx {\nnamespace {\n\n")

set(_table "")

function(_embed_bytes path symbol out_var)
    if(path STREQUAL "" OR NOT EXISTS "${path}")
        set(${out_var} "" PARENT_SCOPE)
        return()
    endif()
    file(READ "${path}" _hex HEX)
    string(LENGTH "${_hex}" _hex_length)
    math(EXPR _size "${_hex_length} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    # A NUL after the payload, not counted in the size: MSL is source text and
    # Metal's compiler wants a terminated string.
    set(${out_var} "const std::uint8_t ${symbol}[] = {${_bytes}0x00};\nconstexpr std::size_t ${symbol}_size = ${_size};\n" PARENT_SCOPE)
endfunction()

foreach(_line IN LISTS _lines)
    if(_line STREQUAL "")
        continue()
    endif()
    string(REPLACE "|" ";" _fields "${_line}")
    list(LENGTH _fields _count)
    list(GET _fields 0 _symbol)
    list(GET _fields 1 _stage)
    list(GET _fields 2 _spv)
    list(GET _fields 3 _msl)
    set(_dxbc "")
    if(_count GREATER 4)
        list(GET _fields 4 _dxbc)
    endif()

    _embed_bytes("${_spv}" "${_symbol}_spirv" _a)
    _embed_bytes("${_msl}" "${_symbol}_msl" _b)
    _embed_bytes("${_dxbc}" "${_symbol}_dxbc" _c)
    string(APPEND _body "${_a}${_b}${_c}\n")

    if(_stage STREQUAL "vert")
        set(_stage_enum "ShaderStage::Vertex")
    else()
        set(_stage_enum "ShaderStage::Fragment")
    endif()
    string(REPLACE "_vert" "" _name "${_symbol}")
    string(REPLACE "_frag" "" _name "${_name}")
    if(_c STREQUAL "")
        set(_dxbc_ref "nullptr, 0")
    else()
        set(_dxbc_ref "${_symbol}_dxbc, ${_symbol}_dxbc_size")
    endif()
    string(APPEND _table "    {\"${_name}\", ${_stage_enum}, ${_symbol}_spirv, ${_symbol}_spirv_size, ${_symbol}_msl, ${_symbol}_msl_size, ${_dxbc_ref}},\n")
endforeach()

string(APPEND _body "const EmbeddedShader kShaders[] = {\n${_table}};\n\n}  // namespace\n\n")
string(APPEND _body "const EmbeddedShader* find_embedded_shader(std::string_view name, ShaderStage stage) {\n")
string(APPEND _body "    for (const auto& shader : kShaders) {\n        if (shader.stage == stage && name == shader.name) {\n            return &shader;\n        }\n    }\n    return nullptr;\n}\n\n}  // namespace sf::gfx\n")

file(WRITE "${OUTPUT}.tmp" "${_body}")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
